name: "FE CI"

on:
    pull_request:
        branches: [master]
        
jobs:
    run_tests:
        runs_on: ubuntu_latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
                with: 
                    node-version: 12
            - run: npm ci
            - run: npm test
            - run: npm build

